spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogdb?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: '!Lee201204098'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true      # SQL 쿼리 로깅
    hibernate:
      ddl-auto: create  # 테이블 자동 생성
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true  # Hibernate 이후 data.sql 실행

  h2:
    console:
      enabled: true
jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot

