spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  jpa:
    show-sql: true      # SQL 쿼리 로깅
    hibernate:
      ddl-auto: create  # 테이블 자동 생성
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true  # Hibernate 이후 data.sql 실행

  h2:
    console:
      enabled: true
jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot

